### ISSUE TITLE
Getting runtime error while trying Texturize Demo: Grass in Colab

### ISSUE THREAD

**Issue by ishu121992** [texturedesign/texturize#44]
/usr/local/lib/python3.9/dist-packages/texturize/critics.py:116: UserWarning: Using a target size (torch.Size([256, 256])) that is different to the input size (torch.Size([256, 253])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  yield F.mse_loss(current, source)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-8-e00d0ffeb6f5>](https://localhost:8080/#) in <cell line: 3>()
      1 display_widget = io.show_result_in_notebook()
      2 
----> 3 for result in synthesize(grass1):
      4     display_widget.update(result)

15 frames
[/usr/local/lib/python3.9/dist-packages/torch/functional.py](https://localhost:8080/#) in broadcast_tensors(*tensors)
     72     if has_torch_function(tensors):
     73         return handle_torch_function(broadcast_tensors, tensors, *tensors)
---> 74     return _VF.broadcast_tensors(tensors)  # type: ignore[attr-defined]
     75 
     76 

RuntimeError: The size of tensor a (253) must match the size of tensor b (256) at non-singleton dimension 1

**Comment by alexjc** [comment]
Thank you! It's a known issue and I almost have the fix ready.

**Comment by alexjc** [comment]
Fix is checked in and will be in the next release!
